version: "2"
services:
  registry:
    build: ./registry-service
    networks:
      - swos
    ports:
      - "1111:1111"
  artist:
    build: ./artist-service
    networks:
      - swos
  cd:
    build: ./cd-service
    networks:
      - swos
  artist-cd:
    build: ./artist-cd-service
    networks:
      - swos
  frontend:
    build: ./frontend-service
    networks:
      - swos
    ports:
      - "8080:8080"
  monitor:
    build: ./monitor-service
    networks:
      - swos
    ports:
      - "9999:9999"
networks:
  swos: