spring:
  jackson:
    dateFormat: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      writeDatesAsTimestamps: false
  application:
    name: artist-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

server:
  port: 3333