# Spring properties
spring:
  application:
    name: monitor-service

# Discovery Server Access
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://registry:1111/eureka/

# HTTP Server
server:
  port: 9999   # HTTP (Tomcat) port

# Service Monitoring
turbine:
  clusterNameExpression: new String("default")
  appConfig: artist-cd-service