# Spring properties
spring:
  application:
    name: frontend-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:1111/eureka/

# API Proxy configuration
zuul:
  routes:
    cd-service:
      path: /cds/**
      serviceId: cd-service
      stripPrefix: false
    artist-service:
      path: /artists/**
      serviceId: artist-service
      stripPrefix: false
    artist-cd-service:
      path: /artistCd/**
      serviceId: artist-cd-service
      stripPrefix: false